- name: "{{ zfs_command_name | capitalize }}"
  become: true
  ansible.builtin.command:
    cmd: "{{ zfs_command }}"
  failed_when: zfs_command_exec.rc != 0
  changed_when: "zfs_command != 'true'"
  register: zfs_command_exec
  when: not zfs_debug | default(false)

- name: Gather zpool facts from pool
  community.general.zfs_facts:
    name: "{{ zpool.name }}"
    recurse: true
    parsable: true
  when:
  - zfs_action in ["destroy", "rename"]
