---
- name: Install zfs-utils
  become: true
  community.general.pacman:
    name: zfs-utils
    state: present
    update_cache: true
  tags:
  - molecule-idempotence-notest


- name: Add zfs kernel module
  become: true
  community.general.modprobe:
    name: zfs
    state: present
    params: "{{ zfs_module_params | join(' ') if zfs_module_params is defined else omit }}"
    persistent: "present"
