# SPDX-License-Identifier: MIT-0
---
# handlers file for systemd_networkd

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_networkd_chroot_path is not defined
