---
- name: Cleanup
  hosts: all
  gather_facts: false
  tasks:
  - name: Wait for docker instances to be created
    ansible.builtin.wait_for_connection:
      timeout: 2
    register: wait_for_instances
    failed_when: false
    changed_when: wait_for_instances.elapsed >= 1

  - name: Cleanup dummy devices
    become: true
    when: wait_for_instances is not changed
    ansible.builtin.shell:
      executable: /bin/bash
      cmd: |
        set -o pipefail
        losetup -j {{ item }} -n -O name | xargs -I{} losetup -d {}
    register: losetup_command
    changed_when: losetup_command.rc != 0
    failed_when: losetup_command.rc != 0
    with_items:
    - /dummydev0
    - /dummydev1
