- name: Gather the package facts
  block:
  - name: Gather the package facts Debian
    become: true
    ansible.builtin.package_facts:
      manager: auto
  rescue:
  # - name: Ensure sudo is installed
  #   become: true
  #   become_method: ansible.builtin.su
  #   ansible.builtin.package:
  #     name: sudo
  #     state: present
  #   # when:
  #   # - "'sudo' not in ansible_facts.packages"
  - name: Ensure python3-apt is installed
    become: true
    ansible.builtin.package:
      name:
      - python3-apt
      state: present
  - name: Gather the package facts
    become: true
    ansible.builtin.package_facts:
      manager: auto

- name: Set pre-upgrade kernel version fact on Debian
  ansible.builtin.set_fact:
    pre_upgrade_kernel: "{{ ansible_facts.packages | dict2items | selectattr('key', 'match', '^linux-image-[A-Za-z0-9]+$') | map(attribute='value') | first | map(attribute='version') }}"
  when:
  - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
