- name: Update and upgrade apt packages
  become: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 15
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
    cache_valid_time: 3600
    autoclean: true
    autoremove: true
  notify:
  - Reboot
  tags:
  - molecule-idempotence-notest
