- name: Set helm_arch as amd64
  ansible.builtin.set_fact:
    helm_arch: amd64
  when:
  - not helm_arch|default(false)
  - ansible_facts.architecture == "x86_64"

- name: Set helm_arch as i386
  ansible.builtin.set_fact:
    helm_arch: i386
  when:
  - not helm_arch|default(false)
  - ansible_facts.architecture == "i386"

- name: Set helm_arch as arm64
  ansible.builtin.set_fact:
    helm_arch: amd64
  when:
  - not helm_arch|default(false)
  - |
    ( ansible_facts.architecture is search("arm") and
      ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Set helm_arch as arm
  ansible.builtin.set_fact:
    helm_arch: arm
  when:
  - helm_arch is undefined or not helm_arch|default(false)
  - ansible_facts.architecture is search("arm")
  - ansible_facts.userspace_bits == "32"
