- name: Check if helm exists
  become: true
  ansible.builtin.command: "which helm"
  register: which_helm_command
  changed_when: false
  failed_when: false

- name: Uninstall helm-diff plugin
  when: which_helm_command.rc == 0
  kubernetes.core.helm_plugin:
    plugin_name: helm-diff
    state: absent

- name: Remove helm
  become: true
  ansible.builtin.file:
    path: "{{ helm_install_path }}/helm"
    state: absent
