---
- name: Install Arch linux deps for smartd
  become: true
  community.general.pacman:
    name:
    - smartmontools
    - run-parts
    state: present
    update_cache: true
  tags:
  - molecule-idempotence-notest
