---
# handlers file for smartd
- name: Restart smartd
  become: true
  ansible.builtin.systemd_service:
    name: smartd
    state: restarted
  when:
  - "'smartd.service' in ansible_facts.services"

- name: Systemd daemon reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
