---
# tasks file for cilium
- name: Combine cilium_helm_values_override into cilium_helm_values
  when:
  - cilium_helm_values_override is defined
  ansible.builtin.set_fact:
    cilium_helm_values: "{{ (cilium_helm_values | default({})) | combine(cilium_helm_values_override, recursive=true, list_merge='replace') }}"

- name: Install ciliumctl
  ansible.builtin.import_tasks: cilium-cli.yml
  become: true
  when:
  - cilium_cli_install | default(false)

- name: Install dependencies
  ansible.builtin.include_tasks: "prepare-{{ ansible_os_family | lower }}.yml"

- name: Set cilium version
  when: cilium_version | default("latest") == "latest"
  block:
  - name: Get list of cilium github releases
    run_once: true
    ansible.builtin.uri:
      url: https://api.github.com/repos/cilium/cilium/releases/latest
      return_content: true
    register: cilium_releases_json
  - name: Set cilium latest as fact
    ansible.builtin.set_fact:
      cilium_version: "{{ cilium_releases_json.json.tag_name | trim | regex_replace('^v', '') }}"
    when: not cilium_releases_json.failed

- name: Check if can access cluster with kubectl
  become: true
  ansible.builtin.command: "kubectl get nodes"
  register: kubectl_command
  failed_when: cilium_require_install | default(true) and kubectl_command.rc != 0
  changed_when: false

- name: Determine cilium_kubeconfig fact if not set
  when:
  - cilium_kubeconfig | default("") == ""
  ansible.builtin.import_tasks: resolve-kubeconfig.yml

- name: Get current user name
  ansible.builtin.command: whoami
  register: current_user_name
  changed_when: current_user_name.rc != 0
  when: ansible_user is undefined or ansible_user == ""

- name: Install cilium in python venv
  when: kubectl_command.rc == 0
  vars:
    venv_user: "{{ ansible_user | default(current_user_name.stdout) | default(omit) }}"
    virtualenv_command: "{{ 'python -m venv' if ansible_facts['os_family'] == 'Archlinux' else 'virtualenv' }}"
  block:
  - name: Get user home path
    ansible.builtin.shell:
      executable: /bin/bash
      cmd: |-
        set -o pipefail
        grep -E {{ venv_user | default('root') }}: /etc/passwd | awk -F: '{ print $6 }'
    failed_when: user_home_path.rc != 0
    changed_when: false
    register: user_home_path

  - name: Ensure the virtual environment exists
    ansible.builtin.pip:
      name: packaging
      virtualenv: "{{ user_home_path.stdout }}/.ansible-venv"
      virtualenv_command: "{{ virtualenv_command }}"

  - name: Run commands in venv
    vars:
      ansible_python_interpreter: "{{ venv_python }}"
      venv_dir: "{{ user_home_path.stdout }}/.ansible-venv"
      venv_python: "{{ venv_dir }}/bin/python"
    block:
    - name: Install python pre-requisites
      ansible.builtin.pip:
        name: kubernetes
    - name: Install cilium with helm
      environment:
        K8S_AUTH_KUBECONFIG: "{{ cilium_kubeconfig }}"
      block:
      - name: Install cilium with helm
        ansible.builtin.include_tasks: helm-install.yml

  # end block Run commands in venv
# end block Install cilium in python venv

- name: Use k3s_bin_dir as cilium_k3s_killalld_dir value if defined
  when: k3s_bin_dir is defined
  ansible.builtin.set_fact:
    cilium_k3s_killalld_dir: "{{ k3s_bin_dir }}/k3s-killall.sh.d/"

- name: Copy remove cilium cleanup script to k3s-killall.sh.d
  become: true
  when:
  - cilium_k3s_killall_script | default(false)
  - cilium_k3s_killalld_dir | default("") | length > 1
  ansible.builtin.template:
    src: "99-remove-cilium-interfaces.sh.j2"
    dest: "{{ cilium_k3s_killalld_dir }}/99-remove-cilium-interfaces.sh"
    owner: root
    group: root
    mode: "0700"
