---
- name: Resolve default kubeconfig path # noqa: var-naming[no-role-prefix]
  ansible.builtin.command: "realpath {{ cilium_default_kubeconfig_path }}"
  register: realpath_kubeconfig_command
  failed_when: false
  changed_when: false

- name: "Stat kubeconfg" # noqa: var-naming[no-role-prefix]
  ansible.builtin.stat:
    path: "{{ realpath_kubeconfig_command.stdout }}"
  register: kubeconfig_file

- name: Set cilium_kubeconfig fact
  ansible.builtin.set_fact:
    cilium_kubeconfig: "{{ realpath_kubeconfig_command.stdout | trim if kubeconfig_file.stat.exists else cilium_default_kubeconfig }}"
