  - name: "Cleanup dummy devices for vg {{ vg.name }}"
    become: true
    ansible.builtin.shell:
      executable: /bin/bash
      cmd: |
        set -o pipefail
        losetup -j {{ item }} -n -O name | xargs -I{} losetup -d {}
    register: losetup_command
    changed_when: losetup_command.rc != 0
    failed_when: losetup_command.rc != 0
    with_items: "{{ vg.pvs }}"
