---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: kubectl-install
  image: debian:12
  dockerfile: Dockerfile.debian.j2
  pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: molecule
verifier:
  name: ansible
