---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check kubectl command works
    ansible.builtin.command: "kubectl version --client"
    changed_when: false
    register: kubectl_version_command

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - kubectl_version_command.rc == 0
