---
- name: Converge
  hosts: all
  tasks:
  - name: Read loop device from disk
    ansible.builtin.slurp:
      src: /loopback-devicename.txt
    register: loopback_devicename

  - name: "Include archlinux_install role"
    ansible.builtin.include_role:
      name: "archlinux_install"
    vars:
      archlinux_install_disks:
      - device: "{{ loopback_devicename.content | b64decode }}"
        wipe: false
        partitions:
        - name: ESP
          # start: 0%
          end: 512MiB
          flags:
          - boot
          - esp
          type: primary
        - name: RootFS
          start: 512MiB
          end: '100%'
          type: primary
