---
dependency:
  name: shell
  command: "${MOLECULE_PROJECT_DIRECTORY}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: end-to-end-server
  image: archlinux:base
  dockerfile: ../../molecule-shared/Dockerfile.archlinux-systemd.j2
  groups:
  - k3s_servers
  - helm_hosts
  - k3s_hosts
  - calico_hosts
  - fluxcd_hosts
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
  networks:
  - name: end-to-end-cluster
  docker_networks:
  - name: end-to-end-cluster

- name: end-to-end-agent
  image: debian:12
  dockerfile: ../../molecule-shared/Dockerfile.debian-systemd.j2
  groups:
  - k3s_agents
  - k3s_hosts
  - lvm_hosts
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
  networks:
  - name: end-to-end-cluster
  docker_networks:
  - name: end-to-end-cluster

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  inventory:
    group_vars:
      all:
        fluxcd_bootstrap_install_only: true
        fluxcd_bootstrap_allow: true
        ansible_user: molecule
        k3s_allow_swap: true
        calico_install_wait_retries: 120
        calico_uninstall_wait_timeout: "5m0s"
        calico_uninstall_retries: 10
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
      lvm_hosts:
        lvm_vgs:
        - name: endtoend.data
          pvs:
          - /dummydev7
          - /dummydev8
          lvols:
          - name: emptyVol
            size: 50%VG
            opts: --zero n
        lvm_lvols:
        - name: anotherVol
          vg: endtoend.data
          size: 50%VG
          opts: --zero n
      k3s_servers:
        k3s_role: server
        k3s_node_taints:
        - node-role.kubernetes.io/master=true:NoSchedule
        k3s_node_labels:
        - node_type=master
        k3s_kubescheduler_config:
          leaderElection:
            leaderElect: true
          extenders:
          - urlPrefix: "http://127.0.0.1:9251"
            filterVerb: "predicate"
            prioritizeVerb: "prioritize"
            nodeCacheCapable: false
            weight: 100
            managedResources:
            - name: "topolvm.io/capacity"
              ignoredByScheduler: true
        k3s_config:
          snapshotter: native
          write-kubeconfig-mode: 644
          disable:
          - servicelb
          - traefik
          - local-storage
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          cluster-dns: 10.43.0.10
          flannel-backend: none
          disable-cloud-controller: true
          disable-network-policy: true
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0
        calico_helm_values:
          installation:
            registry: quay.io
            enabled: true
            controlPlaneTolerations:
            - key: "CriticalAddonsOnly"
              operator: "Equal"
              value: "true"
              effect: "NoSchedule"
            calicoNetwork:
              linuxDataplane: "Iptables"
              containerIPForwarding: "Enabled"
              ipPools:
              - blockSize: 26
                allowedUses:
                - Workload
                - Tunnel
                cidr: 10.42.0.0/16
                ipipMode: CrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
                vxlanMode: Never
      k3s_agents:
        k3s_role: agent
        k3s_config:
          snapshotter: native
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0

verifier:
  name: ansible
