---
- name: Prepare ssd_nodes
  hosts: ssd_nodes

- name: Create cluster
  ansible.builtin.import_playbook: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') | default('../..', true) }}/playbooks/turingpi_create_cluster.yml"
