---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: fluxcd-multi-cluster-server-1
  image: "debian:12"
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
- name: fluxcd-multi-cluster-server-2
  image: "debian:12"
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
- name: fluxcd-multi-cluster-server-3
  image: "debian:12"
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      fluxcd-multi-cluster-server-1:
        fluxcd_bootstrap_key_name: shared
      fluxcd-multi-cluster-server-2:
        fluxcd_bootstrap_key_name: server-2
        fluxcd_bootstrap_ssh_key_type: rsa
      fluxcd-multi-cluster-server-3:
        fluxcd_bootstrap_key_name: shared
    group_vars:
      all:
        k3s_allow_cluster_init: false
        ansible_user: molecule
        k3s_role: server
        k3s_config:
          disable:
          - traefik
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          cluster-dns: 10.43.0.10
          disable-cloud-controller: true
          kube-apiserver-arg:
          - default-not-ready-toleration-seconds=10
          - default-unreachable-toleration-seconds=10
          snapshotter: native
          write-kubeconfig-mode: 644
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0
        fluxcd_bootstrap_install_only: true
        fluxcd_bootstrap_allow: true
        k3s_allow_swap: true
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
verifier:
  name: ansible
