---
# This is an example playbook to execute Ansible tests.
- name: Verify ArchLinux
  hosts: samba-arch
  gather_facts: true
  tasks:
  - name: Populate service facts
    become: true
    ansible.builtin.service_facts:

  - name: Stat file /etc/samba/smb.conf
    ansible.builtin.stat:
      path: "/etc/samba/smb.conf"
    register: verify_samba_conf

  - name: Stat file /etc/conf.d/wsdd"
    ansible.builtin.stat:
      path: "/etc/conf.d/wsdd"
    register: verify_wsdd_conf

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - verify_samba_conf.stat.exists
      - verify_wsdd_conf.stat.exists
      - "'smb.service' in ansible_facts.services"
      - "'avahi-daemon.service' in ansible_facts.services"
      - "'wsdd.service' in ansible_facts.services"
      - "'nmb.service' in ansible_facts.services"
      - "'wsdd2.service' not in ansible_facts.services"

- name: Verify Debian
  hosts: samba-debian
  gather_facts: true
  tasks:
  - name: Populate service facts
    become: true
    ansible.builtin.service_facts:

  - name: Stat file /etc/samba/smb.conf
    ansible.builtin.stat:
      path: "/etc/samba/smb.conf"
    register: verify_samba_conf

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - verify_samba_conf.stat.exists
      - "'smb.service' in ansible_facts.services"
      - "'avahi-daemon.service' in ansible_facts.services"
      - "'wsdd2.service' in ansible_facts.services"
      - "'wsdd.service' not in ansible_facts.services"
      - "'nmb.service' in ansible_facts.services"
