---
# handlers file for superfans
- name: Restart superfans
  become: true
  ansible.builtin.systemd_service:
    name: superfans
    state: restarted
  when:
  - "'superfans.service' in ansible_facts.services"

- name: Systemd daemon reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
