---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Install lvm2
    become: true
    register: lvm_install
    ansible.builtin.package:
      update_cache: true
      name:
      - lvm2

  - name: Get pvs
    become: true
    ansible.builtin.command: "pvdisplay -C -o pv_name --no-headings"
    register: pvdisplay_output
    changed_when: pvdisplay_output.rc != 0

  - name: Get vgs
    become: true
    ansible.builtin.command: "vgdisplay -C -o name --no-headings"
    register: vgdisplay_output
    changed_when: vgdisplay_output.rc != 0

  - name: Get lvs
    become: true
    ansible.builtin.command: "lvdisplay -C -o name --no-headings"
    register: lvdisplay_output
    changed_when: lvdisplay_output.rc != 0

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - lvm_install is changed
      - pvdisplay_output.stdout_lines | length == 0
      - vgdisplay_output.stdout_lines | length == 0
      - lvdisplay_output.stdout_lines | length == 0
