---
dependency:
  name: shell
  command: "COLLECTION_INSTALL=false ${GITHUB_WORKSPACE:-..}/${GITHUB_REPOSITORY:-..}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: dietpi-config
  image: "debian:12"
  dockerfile: ../../../../molecule-shared/Dockerfile.debian-systemd.j2
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  hostname: dietpi
  tty: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        dietpi_configure_root_password: root_root
        dietpi_configure_root_password_salt: salty.Salt
        dietpi_configure_users:
        - name: wahooli
          groups: sudo
          password: qwerty
          authorized_keys:
          - ssh_rsa abcdefg wahooli@dietpi
        dietpi_configure_packages:
        - vim
        - nano
        - nfs-common
verifier:
  name: ansible
