---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: dietpi-config
  image: "debian:12"
  tmpfs:
  - /run
  - /tmp
  volumes:
    - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  hostname: dietpi
  tty: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        dietpi_configure_users:
        - name: wahooli
          groups: sudo
          password: qwerty
          authorized_keys:
          - ssh_rsa abcdefg wahooli@dietpi
        dietpi_configure_packages:
        - vim
        - nano
        - nfs-common
verifier:
  name: ansible
