---
dependency:
  name: shell
  command: "COLLECTION_INSTALL=false ${GITHUB_WORKSPACE:-..}/${GITHUB_REPOSITORY:-..}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: k3s-server-upgrade-debian
  image: "debian:12"
  dockerfile: ../../../../molecule-shared/Dockerfile.debian-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
- name: k3s-server-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
        k3s_skip_prepare: true
        k3s_role: server
        k3s_config:
          snapshotter: native
          write-kubeconfig-mode: 644
verifier:
  name: ansible
