---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: k3s-server-upgrade
  image: "debian:11"
  tmpfs:
  - /run
  - /tmp
  volumes:
    - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      k3s-server-upgrade:
        ansible_user: molecule
        k3s_skip_prepare: true
        k3s_role: server
        k3s_config:
          snapshotter: native
          write-kubeconfig-mode: 644
verifier:
  name: ansible
