---
- name: Prepare
  hosts: all
  tasks:
  - name: "Install older version of k3s"
    ansible.builtin.include_role:
      name: "k3s"
    vars:
      k3s_skip_prepare: false
      k3s_version: v1.26.3+k3s1
      # k3s_role: server
      # k3s_config:
      #   snapshotter: native
      #   write-kubeconfig-mode: 644
