---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Wait for nodes to be ready
    ansible.builtin.command: "kubectl get nodes"
    register: nodes_ready
    until:
    - '" NotReady " not in nodes_ready.stdout'
    changed_when: nodes_ready.rc != 0
    retries: 120
    delay: 1

  - name: Check cilium cli is installed
    ansible.builtin.command: "cilium version --client"
    register: cilium_cli_version_output
    failed_when: cilium_cli_version_output.rc != 0
    changed_when: false

  - name: Verify cilium status
    become: true
    ansible.builtin.command: "cilium status"
    register: cilium_status
    failed_when: cilium_status.rc != 0
    changed_when: false
    environment:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - cilium_cli_version_output is success
      - nodes_ready is success
      - cilium_status is success
