---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
- name: k3s-server
  image: "debian:12"
  tmpfs:
  - /run
  - /tmp
  volumes:
    - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  inventory:
    host_vars:
      k3s-server:
        ansible_user: molecule
        k3s_role: server
        k3s_containerd_pause_image: rancher/mirrored-pause:3.9
        k3s_kubescheduler_config:
          leaderElection:
            leaderElect: true
          extenders:
          - urlPrefix: "http://127.0.0.1:9251"
            filterVerb: "predicate"
            prioritizeVerb: "prioritize"
            nodeCacheCapable: false
            weight: 100
            managedResources:
            - name: "topolvm.io/capacity"
              ignoredByScheduler: true
        k3s_config:
          snapshotter: native
          write-kubeconfig-mode: 644
          kube-scheduler-arg:
          - bind-address=0.0.0.0
verifier:
  name: ansible
