- name: Create namespace
  when:
  - secret.namespace is defined
  kubernetes.core.k8s:
    name: "{{ secret.namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: Create secret
  when:
  - secret.name is defined
  - secret.data is defined
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: "{{ secret.name }}"
        namespace: "{{ secret.namespace | default(kubernetes_secret_namespace | default('default')) }}"
      stringData: "{{ secret.data }}"
