---
# tasks file for kubernetes_secret
- name: Gather pip package facts
  community.general.pip_package_info:
  register: pip_facts

- name: Install python pre-requisites
  when: "'kubernetes' not in pip_facts.packages.pip"
  ansible.builtin.pip:
    name: kubernetes
    extra_args: "{{ '--break-system-packages' if ansible_distribution_major_version | string == '12' else '' }}"

- name: Create secrets
  when:
  - kubernetes_secret_data is defined
  ansible.builtin.include_tasks: create-secret-with-ns.yml
  loop: "{{ kubernetes_secret_data | default(omit) }}"
  loop_control:
    loop_var: secret
