---
- name: Converge
  hosts: all

- name: Import turingpi_create_cluster playbook
  ansible.builtin.import_playbook: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') | default('../..', true) }}/playbooks/turingpi_create_cluster.yml"
