---
# This is an example playbook to execute Ansible tests.
- name: Verify servers
  hosts: k3s_servers
  gather_facts: false
  tasks:
  - name: Wait for nodes to be ready
    ansible.builtin.command: "kubectl get nodes"
    register: nodes_ready
    until:
    - '" NotReady " not in nodes_ready.stdout'
    changed_when: nodes_ready.rc != 0
    retries: 60
    delay: 1

  - name: Check calicoctl is installed
    ansible.builtin.command: "calicoctl node status"
    register: calicoctl_version_output
    failed_when: calicoctl_version_output.rc == 127
    changed_when: calicoctl_version_output.rc > 1

  - name: Check server taint
    ansible.builtin.command: "kubectl get nodes -o custom-columns=TAINTS:.spec.taints[].key --no-headers raspberry-pi-server-01"
    register: server_taints
    changed_when: server_taints.rc != 0

  - name: Check agent labels
    ansible.builtin.command: |
      kubectl get nodes -o jsonpath="{.metadata.labels.node_type}" --no-headers raspberry-pi-agent-01
    register: node_type_label
    changed_when: node_type_label.rc != 0

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - calicoctl_version_output is success
      - nodes_ready is success
      - server_taints.stdout == "node-role.kubernetes.io/master"
      - node_type_label.stdout == "storage"
