FROM {{ item.image }}

ENV container=docker \
    ANSIBLE_USER=molecule \
    DEPLOY_GROUP=deployer \
    SUDO_GROUP={{'sudo' if 'debian' in item.image else 'wheel' }}

RUN {{ 'microdnf' if 'minimal' in item.image else 'dnf' }} install -y sudo {{ 'dnf' if 'minimal' in item.image else '' }} \
    && set -xe \
    && groupadd -r ${ANSIBLE_USER} \
    && groupadd -r ${DEPLOY_GROUP} \
    && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
    && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
    && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
    && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

STOPSIGNAL SIGRTMIN+3
VOLUME [ "/tmp", "/run", "/run/lock" ]
WORKDIR /
