---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: rockylinux-minimal-9-update-os
  dockerfile: Dockerfile.rocky.j2
  image: rockylinux:9-minimal
  pre_build_image: false
  tmpfs:
  - /run
  - /tmp
- name: rockylinux-9-update-os
  dockerfile: Dockerfile.rocky.j2
  image: rockylinux:9
  pre_build_image: false
  tmpfs:
  - /run
  - /tmp
- name: debian-11-update-os
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
  image: debian:11
  tmpfs:
  - /run
  - /tmp
- name: debian-12-update-os
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
  image: debian:12
  tmpfs:
  - /run
  - /tmp
- name: arch-update-os
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux.j2
  pre_build_image: false
  image: archlinux:base
  tmpfs:
  - /run
  - /tmp
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
        pre_upgrade_kernel: 1
        post_upgrade_kernel: 2
verifier:
  name: ansible
