---
- name: Converge
  hosts: all
  collections:
  - wahooli.k3s

- name: Import turingpi_create_cluster playbook
  ansible.builtin.import_playbook: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') }}/playbooks/turingpi_create_cluster.yml"