- name: Ensure dbus is installed
  ansible.builtin.apt:
    name: "dbus"
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: Start dbus
  become: true
  ansible.builtin.systemd_service:
    name: dbus
    state: started
    daemon_reload: true
    enabled: true

- name: "Set hostname to {{ inventory_hostname }}"
  become: true
  when:
  - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
