- name: "Set hostname to {{ inventory_hostname }}"
  become: true
  when:
  - ansible_connection not in [ "container", "docker", "community.docker.docker" ]
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd
