---
dependency:
  name: shell
  command: "COLLECTION_INSTALL=false ${GITHUB_WORKSPACE:-..}/${GITHUB_REPOSITORY:-..}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: fluxcd-cluster-server-debian
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
  groups:
  - server
  networks:
  - name: fluxcd-cluster-debian
  docker_networks:
  - name: fluxcd-cluster-debian
- name: fluxcd-cluster-agent-debian
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
  groups:
  - agent
  networks:
  - name: fluxcd-cluster-debian
  docker_networks:
  - name: fluxcd-cluster-debian
- name: fluxcd-cluster-server-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
  groups:
  - server
  - arch
  networks:
  - name: fluxcd-cluster-arch
  docker_networks:
  - name: fluxcd-cluster-arch
- name: fluxcd-cluster-agent-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux-systemd.j2
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
  groups:
  - agent
  - arch
  networks:
  - name: fluxcd-cluster-arch
  docker_networks:
  - name: fluxcd-cluster-arch
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    host_vars:
      fluxcd-cluster-agent-arch:
        k3s_config:
          server: https://fluxcd-cluster-server-arch:6443
          snapshotter: native
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
      fluxcd-cluster-agent-debian:
        k3s_config:
          server: https://fluxcd-cluster-server-debian:6443
          snapshotter: native
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
    group_vars:
      arch:
        k3s_containerd_use_crun: true
      all:
        # run as root to test role works with that also
        # ansible_user: molecule
        fluxcd_bootstrap_install_only: true
        fluxcd_bootstrap_allow: true
        k3s_allow_swap: true
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
      server:
        k3s_role: server
        k3s_config:
          disable:
          - traefik
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          cluster-dns: 10.43.0.10
          disable-cloud-controller: true
          kube-apiserver-arg:
          - default-not-ready-toleration-seconds=10
          - default-unreachable-toleration-seconds=10
          snapshotter: native
          write-kubeconfig-mode: 644
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0
      agent:
        k3s_role: agent

verifier:
  name: ansible
