---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: fluxcd-cluster-server
  gather_facts: false
  tasks:
  - name: Check flux bin is found in path
    ansible.builtin.command: "which flux"
    failed_when: false
    changed_when: which_flux.rc != 0
    register: which_flux

  - name: Check flux command works
    ansible.builtin.command: "flux --help"
    failed_when: false
    changed_when: flux_cli_help.rc != 0
    register: flux_cli_help

  - name: "Stat file /root.fluxcd/fluxcd/id_ed25519"
    ansible.builtin.stat:
      path: "/root/.fluxcd/fluxcd/id_ed25519"
    register: flux_private_key

  - name: "Stat file /root/.fluxcd/fluxcd/id_ed25519.pub"
    ansible.builtin.stat:
      path: "/root/.fluxcd/fluxcd/id_ed25519.pub"
    register: flux_public_key

  - name: Check cluster FluxCD installation
    environment:
      K8S_AUTH_KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
      KUBECONFIG: "/etc/rancher/k3s/k3s.yaml"
    block:
    - name: Check cluster FluxCD installation
      ansible.builtin.command: "flux check"
      failed_when: false
      changed_when: flux_cli_check.rc != 0
      register: flux_cli_check

  - name: Assert
    ansible.builtin.assert:
      that:
      - flux_cli_help is not changed
      - which_flux is not changed
      - flux_private_key.stat.exists
      - flux_public_key.stat.exists
      - flux_cli_check is not changed