---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: kubectl-upgrade
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
        kubectl_version: v1.29.2
verifier:
  name: ansible
