---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check kubectl command works
    ansible.builtin.command: "kubectl version --client --output=json"
    changed_when: false
    register: kubectl_version_command

  - name: Run assertions
    ansible.builtin.assert:
      that:
      - (kubectl_version_command.stdout | from_json).clientVersion.gitVersion == 'v1.29.2'
      - kubectl_version_command.rc == 0
