---
# tasks file for reboot
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check if reboot-required exists
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot
  become: true
  failed_when: false
  when:
  - reboot_required.stat.exists
  ansible.builtin.reboot:
    reboot_timeout: 600

- name: Wait for system to become reachable again
  ansible.builtin.wait_for_connection:
    delay: 15
    timeout: 600
  when: reboot_required.stat.exists
