---
# tasks file for reboot
- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Check if reboot-required exists
  become: true
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot
  become: true
  when:
  - reboot_required.stat.exists
  ansible.builtin.reboot:
    reboot_command: "{{ reboot_command | default('systemctl reboot') }}"
    reboot_timeout: 600
