---
# tasks file for nfs
- name: Populate service facts
  become: true
  when: ansible_facts.services is not defined
  ansible.builtin.service_facts:

- name: Install deps
  ansible.builtin.include_tasks: "deps-{{ ansible_os_family | lower }}.yaml"

- name: Ensure /etc/exports.d exists
  become: true
  ansible.builtin.file:
    path: "/etc/exports.d"
    state: directory
    owner: root
    group: root
    mode: "u=rw,go=r,a+X"
    modification_time: preserve
    access_time: preserve

- name: Apply nfs exports
  become: true
  ansible.builtin.template:
    src: "exports.j2"
    dest: "{{ nfs_exports_file }}"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nfs

- name: Apply /etc/nfs.conf
  become: true
  ansible.builtin.template:
    src: "nfs.conf.j2"
    dest: "/etc/nfs.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart nfs

- name: Enable and start nfs-server
  become: true
  ansible.builtin.systemd_service:
    name: nfs-server
    state: started
    enabled: true
  when:
  - "'nfs-server.service' not in ansible_facts.services"
