FROM {{ item.image }}

ENV container=docker \
    ANSIBLE_USER=molecule \
    DEPLOY_GROUP=deployer \
    SUDO_GROUP={{'sudo' if 'debian' in item.image else 'wheel' }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo \
    procps \
    iproute2 \
    python3 ca-certificates \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean \
    && touch -a -m -d "2 weeks ago" /var/lib/apt/lists/ \
    && set -xe \
    && groupadd -r ${ANSIBLE_USER} \
    && groupadd -r ${DEPLOY_GROUP} \
    && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
    && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
    && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
    && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

STOPSIGNAL SIGRTMIN+3
VOLUME [ "/tmp", "/run", "/run/lock" ]
WORKDIR /
