---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: fluxcd-install-debian
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
- name: fluxcd-install-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux.j2
  pre_build_image: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
verifier:
  name: ansible
