---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: fluxcd-install-debian
  image: debian:12
  dockerfile: Dockerfile.debian.j2
  pre_build_image: false
- name: fluxcd-install-arch
  image: archlinux:base
  dockerfile: Dockerfile.arch.j2
  pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: molecule
verifier:
  name: ansible
