---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Check flux bin is found in path
    ansible.builtin.command: "which flux"
    failed_when: false
    changed_when: which_flux.rc != 0
    register: which_flux

  - name: Check flux command works
    ansible.builtin.command: "flux --help"
    failed_when: false
    changed_when: flux_cli_help.rc != 0
    register: flux_cli_help

  - name: "Stat file /home/molecule/.fluxcd/fluxcd/id_ed25519"
    ansible.builtin.stat:
      path: "/home/molecule/.fluxcd/fluxcd/id_ed25519"
    register: flux_private_key

  - name: "Stat file /home/molecule/.fluxcd/fluxcd/id_ed25519.pub"
    ansible.builtin.stat:
      path: "/home/molecule/.fluxcd/fluxcd/id_ed25519.pub"
    register: flux_public_key

  - name: Assert
    ansible.builtin.assert:
      that:
      - not flux_private_key.stat.exists
      - not flux_public_key.stat.exists
      - flux_cli_help is not changed
      - which_flux is not changed