---
dependency:
  name: shell
  command: "COLLECTION_INSTALL=false ${GITHUB_WORKSPACE:-..}/${GITHUB_REPOSITORY:-..}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: k3s-cilium-uninstall-debian
  dockerfile: Dockerfile.debian.j2
  image: debian:12
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
- name: k3s-cilium-uninstall-arch
  dockerfile: Dockerfile.arch.j2
  image: archlinux:base
  tmpfs:
  - /run
  - /tmp
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        cilium_helm_values:
          hubble:
            enabled: false
          envoy:
            enabled: false
          cni:
            logFile: /dev/null
          operator:
            replicas: 1
        ansible_user: molecule
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
          feature-gates:
            GracefulNodeShutdown: true
          node-status-update-frequency: 5s
        k3s_role: server
        k3s_config:
          disable:
          - servicelb
          - traefik
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          cluster-dns: 10.43.0.10
          flannel-backend: none
          disable-cloud-controller: true
          disable-network-policy: true
          kube-apiserver-arg:
          - default-not-ready-toleration-seconds=10
          - default-unreachable-toleration-seconds=10
          snapshotter: native
          write-kubeconfig-mode: 644
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0

verifier:
  name: ansible
