---
- name: Converge
  hosts: all
  tasks:
  - name: Set up loopback devices
    ansible.builtin.include_tasks: tasks/converge_iterate-vgs.yaml
    with_items: "{{ lvm_vgs }}"
    loop_control:
      loop_var: vg

  - name: Update lvm_vgs fact
    ansible.builtin.set_fact:
      lvm_vgs: "{{ new_lvm_vgs }}"

  - name: "Include lvm role"
    ansible.builtin.include_role:
      name: "lvm"
