---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: docker
platforms:
- name: lvm-test-debian
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian-systemd.j2
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
- name: lvm-test-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux-systemd.j2
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
    host_vars:
      lvm-test-debian:
        lvm_vgs:
        - name: vg.testdata.debian
          pvs:
          - /dummydev1
          - /dummydev2
          lvols:
          - name: emptyPool
            size: 50%VG
            opts: --zero n
        lvm_lvols:
        - name: mountedPool
          vg: vg.testdata.debian
          size: 50%VG
          opts: --zero n
      lvm-test-arch:
        lvm_vgs:
        - name: vg.testdata.arch
          pvs:
          - /dummydev7
          - /dummydev8
          lvols:
          - name: emptyPool
            size: 50%VG
            opts: --zero n
        lvm_lvols:
        - name: mountedPool
          vg: vg.testdata.arch
          size: 50%VG
          opts: --zero n
verifier:
  name: ansible
