---
# handlers file for k3s
- name: Systemd daemon reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart K3s
  become: true
  throttle: 1
  when:
  - "'k3s.service' in ansible_facts.services"
  - k3s_systemd_start
  ansible.builtin.systemd_service:
    name: k3s
    state: restarted
    enabled: "{{ k3s_systemd_enable }}"

- name: Reload sysctl
  become: true
  ansible.builtin.command: sysctl -p --system
  register: sysctl_reload_command
  changed_when: sysctl_reload_command.rc != 0
