---
galaxy_info:
  author: wahooli
  description: Configures systemd-networkd
  company: wahooli
  license: MIT
  min_ansible_version: "2.1"
  galaxy_tags:
  - "network"
  - "automation"

dependencies: []
