---
dependency:
  name: shell
  command: "${MOLECULE_PROJECT_DIRECTORY}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: single-server-cluster-server
  image: "debian:12"
  groups:
  - k3s_servers
  - k3s_hosts
  tmpfs:
  - /run
  - /tmp
  volumes:
    - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
  networks:
  - name: molecule-single-server-cluster
  docker_networks:
  - name: molecule-single-server-cluster

- name: single-server-cluster-agent
  image: "debian:12"
  groups:
  - k3s_agents
  - k3s_hosts
  tmpfs:
  - /run
  - /tmp
  volumes:
    - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
  networks:
  - name: molecule-single-server-cluster
  docker_networks:
  - name: molecule-single-server-cluster
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  inventory:
    group_vars:
      k3s_hosts:
        k3s_delete_images_tar_after_first_start: true
        k3s_allow_swap: true
        ansible_user: molecule
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
      k3s_servers:
        k3s_role: server
        k3s_node_taints:
        - node-role.kubernetes.io/master=true:NoSchedule
        k3s_node_labels:
        - node_type=master
        k3s_config:
          snapshotter: native
          write-kubeconfig-mode: 644
          disable:
          - servicelb
          - traefik
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0
      k3s_agents:
        k3s_role: agent
        k3s_node_labels:
        - node_type=agent
        k3s_config:
          snapshotter: native
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0

verifier:
  name: ansible
