- name: Check if k3s-uninstall.sh exists
  become: true
  ansible.builtin.command: "which k3s-uninstall.sh"
  register: which_k3s_uninstall_command
  changed_when: false
  failed_when: false

- name: Run k3s-uninstall.sh
  become: true
  when: which_k3s_uninstall_command.rc == 0
  ansible.builtin.command: "{{ which_k3s_uninstall_command.stdout | trim }}"
  register: k3s_uninstall_command
  changed_when: k3s_uninstall_command.rc != 0
  failed_when: k3s_uninstall_command.rc != 0

- name: Remove /etc/rancher directory
  become: true
  ansible.builtin.file:
    path: "/etc/rancher"
    state: absent

- name: Remove sysctls
  become: true
  ansible.builtin.file:
    path: "{{ sysctl_file }}"
    state: absent
  notify:
  - Reload sysctl
