---
# handlers file for dietpi_configure
- name: Restart sshd
  become: true
  ansible.builtin.systemd_service:
    name: sshd
    state: restarted

- name: Emit reboot required
  become: true
  ansible.builtin.file:
    path: /var/run/reboot-required
    state: touch
    mode: "0644"
    modification_time: preserve
    access_time: preserve

- name: Reboot
  become: true
  when: dietpi_configure_allow_reboot | default(false)
  ansible.builtin.reboot:
    reboot_command: "systemctl reboot"
    reboot_timeout: 60

- name: Reload udev
  ansible.builtin.command: "udevadm control --reload"
  register: udev_reload
  changed_when: udev_reload.rc != 0
