---
- name: Install debian deps for superfans
  become: true
  ansible.builtin.apt:
    pkg:
    - virtualenv
    - git
    - ipmitool
    update_cache: true
    cache_valid_time: 3600
  tags:
  - molecule-idempotence-notest
