---
- name: Install Arch linux deps for superfans
  become: true
  community.general.pacman:
    name:
    - ipmitool
    - python-packaging
    - git
    state: present
    update_cache: true
  tags:
  - molecule-idempotence-notest
