FROM {{ item.image }}

ENV container=docker \
    ANSIBLE_USER=molecule \
    DEPLOY_GROUP=deployer \
    SUDO_GROUP={{'sudo' if 'debian' in item.image else 'wheel' }}

RUN rm -rf /usr/lib/initcpio/* \
    && pacman --noconfirm -Sy \
    sudo \
    iproute2 \
    python \
    python-packaging \
    which \
    && pacman -Syu --noconfirm \
    && rm -rf /var/lib/pacman/sync/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && mkdir -p /mnt \
    && set -xe \
    && groupadd -r ${ANSIBLE_USER} \
    && groupadd -r ${DEPLOY_GROUP} \
    && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
    && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
    && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
    && sed -i "s/^#\s*\(%${SUDO_GROUP}.*\\s\+NOPASSWD:\s\+ALL\)/\1/" /etc/sudoers \
    && pacman-key --init

STOPSIGNAL SIGRTMIN+3
VOLUME [ "/tmp", "/run", "/run/lock" ]
WORKDIR /
