---
- name: Prepare normal_install hosts
  hosts: normal_install
  tasks:
  - name: Install dependencies
    become: true
    community.general.pacman:
      name:
      - mkinitcpio
      - linux
      state: present
      update_cache: true
    when:
    - ansible_facts['os_family'] == "Archlinux"

- name: Prepare archiso hosts
  hosts: archiso
  tasks:
  - name: Install arch-install-scripts
    become: true
    community.general.pacman:
      name: "arch-install-scripts"
      state: present
      update_cache: true

  - name: Create base installation dir
    become: true
    ansible.builtin.command:
      argv:
      - pacstrap
      - -K
      - /mnt
      - base
      - linux
      - mkinitcpio
    args:
      creates: /mnt/bin
