---
# vars file for k3s
# k3s_kubeconfig_default_context_name: default
k3s_systemd_dir: /etc/systemd/system
k3s_kubelet_config_apiversion: kubelet.config.k8s.io/v1beta1
k3s_kubescheduler_config_apiversion: kubescheduler.config.k8s.io/v1
k3s_kernel_modules:
- br_netfilter
- overlay
- ip_conntrack
k3s_debian_install_pkg:
- procps
- kmod
- curl
- zstd
k3s_sysctl_file: /etc/sysctl.d/99-k3s.conf
k3s_config_path: /etc/rancher/k3s
k3s_sysctls:
- name: net.ipv4.ip_forward
  value: 1
- name: net.bridge.bridge-nf-call-iptables
  value: 1
- name: net.bridge.bridge-nf-call-ip6tables
  value: 1
- name: fs.inotify.max_user_watches
  value: 10485760
- name: fs.inotify.max_user_instances
  value: 2560
- name: fs.aio-max-nr
  value: 2560
- name: fs.file-max
  value: 10485760
- name: vm.panic_on_oom
  value: 0
- name: kernel.threads-max
  value: 10485760
