---
# vars file for k3s
kubeconfig_default_context_name: default
systemd_dir: /etc/systemd/system
kubelet_config_apiversion: kubelet.config.k8s.io/v1beta1
kubescheduler_config_apiversion: kubescheduler.config.k8s.io/v1
prepare_debian_install_pkg:
- procps
- kmod
- curl
- zstd
sysctl_file: /etc/sysctl.d/99-k3s.conf
config_path: /etc/rancher/k3s
prepare_sysctls:
- name: net.ipv4.ip_forward
  value: 1
- name: net.bridge.bridge-nf-call-iptables
  value: 1
- name: net.bridge.bridge-nf-call-ip6tables
  value: 1
- name: fs.inotify.max_user_watches
  value: 10485760
- name: fs.inotify.max_user_instances
  value: 2560
- name: fs.aio-max-nr
  value: 2560
- name: fs.file-max
  value: 10485760
# - name: kernel.pid_max 64 bit
#   value: 4194304
# - name: kernel.pid_max 32 bit
#   value: 32768
- name: kernel.threads-max
  value: 10485760
- name: vm.swappiness
  value: 0
