---
- name: "Create 1G dummy device files for vg {{ vg.name }}"
  become: true
  ansible.builtin.command: "dd if=/dev/zero of={{ item }} bs=1M count=1024"
  register: dd_command
  changed_when: dd_command.rc != 0
  failed_when: dd_command.rc != 0
  with_items: "{{ vg.pvs }}"

- name: Set up loopback devices
  ansible.builtin.include_tasks: tasks/prepare_create-pvs.yaml
  with_items: "{{ vg.pvs }}"
  loop_control:
    loop_var: pv
