---
# handlers file for cockpit
- name: Systemd daemon reload
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart cockpit
  become: true
  when:
  - "'cockpit.service' in ansible_facts.services"
  ansible.builtin.systemd_service:
    name: cockpit.socket
    state: restarted
