- name: Get supported instruction set
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /lib/ld-linux-x86-64.so.2 --help | grep supported | awk '{print $1;}' | head -n 1
  failed_when: cachyos_supported_isa.stderr != ''
  changed_when: false
  register: cachyos_supported_isa

- name: Check CachyOS key exists in keyring
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      pacman-key --list-keys | grep {{ archlinux_install_cachyos_key_id }}
  failed_when: false
  changed_when: cachyos_key_exists.stdout == ''
  register: cachyos_key_exists

- name: Import CachyOS pacman key
  when: cachyos_key_exists.stdout == ''
  community.general.pacman_key:
    id: "{{ archlinux_install_cachyos_key_id }}"
    keyserver: "{{ archlinux_install_cachyos_key_server }}"
    force_update: true

- name: Install CachyOS mirrorlists
  when: "pacman_conf | default('/etc/pacman.conf') == '/etc/pacman.conf'"
  block:
  - name: Insert CachyOS base mirror into pacman.conf
    ansible.builtin.blockinfile:
      path: "{{ pacman_conf | default('/etc/pacman.conf') }}"
      append_newline: true
      prepend_newline: true
      backup: true
      insertbefore: "^\\[core\\]"
      block: |
        [cachyos]
        Include = /etc/pacman.d/cachyos-mirrorlist
    tags:
    - molecule-idempotence-notest
  - name: Check cachyos-mirrorlist file exists
    ansible.builtin.stat:
      path: /etc/pacman.d/cachyos-mirrorlist
    register: mirrorlist
  - name: "Download CachyOS base mirrorlist"
    when: not mirrorlist.stat.exists
    ansible.builtin.get_url:
      url: "https://mirror.cachyos.org/cachyos-mirrorlist"
      dest: "/etc/pacman.d/cachyos-mirrorlist"
      owner: root
      group: root
      mode: "0644"
    register: cachyos_mirrorlist_dl
    retries: 10
    until: cachyos_mirrorlist_dl is success
  - name: Comment out nl.cachyos.org mirror
    ansible.builtin.lineinfile:
      dest: /etc/pacman.d/cachyos-mirrorlist
      regexp: '(?i)^(Server = .*//nl.cachyos.org.*)'
      line: '# \1'
      backrefs: true
      state: present
  - name: Install CachyOS mirror lists
    community.general.pacman:
      update_cache: true
      name: "{{ archlinux_install_cachyos_install_packages }}"
    tags:
    - molecule-idempotence-notest
- name: Insert CachyOS mirrors into pacman.conf
  ansible.builtin.blockinfile:
    path: "{{ pacman_conf | default('/etc/pacman.conf') }}"
    append_newline: true
    prepend_newline: true
    backup: true
    insertbefore: "^\\[core\\]"
    block: |
      {%- if cachyos_supported_isa.stdout == "x86-64-v3" -%}
      [cachyos-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist
      [cachyos-core-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist
      [cachyos-extra-v3]
      Include = /etc/pacman.d/cachyos-v3-mirrorlist
      {% elif cachyos_supported_isa.stdout == "x86-64-v4" -%}
      [cachyos-v4]
      Include = /etc/pacman.d/cachyos-v4-mirrorlist
      [cachyos-core-v4]
      Include = /etc/pacman.d/cachyos-v4-mirrorlist
      [cachyos-extra-v4]
      Include = /etc/pacman.d/cachyos-v4-mirrorlist
      {% endif %}
      [cachyos]
      Include = /etc/pacman.d/cachyos-mirrorlist
  tags:
  - molecule-idempotence-notest

- name: Import CachyOS keyring
  ansible.builtin.command:
    cmd: "arch-chroot /mnt pacman-key --recv-keys {{ archlinux_install_cachyos_key_id }} --keyserver {{ archlinux_install_cachyos_key_server }}"
  failed_when: false
  changed_when: false
  when: "pacman_conf | default('/etc/pacman.conf') != '/etc/pacman.conf'"

- name: Sign CachyOS keyring
  ansible.builtin.command:
    cmd: arch-chroot /mnt pacman-key --lsign-key {{ archlinux_install_cachyos_key_id }}
  failed_when: false
  changed_when: false
  when: "pacman_conf | default('/etc/pacman.conf') != '/etc/pacman.conf'"

- name: Refresh package cache
  when: "pacman_conf | default('/etc/pacman.conf') == '/etc/pacman.conf'"
  community.general.pacman:
    update_cache: true

- name: Override archlinux_install_kernel value
  ansible.builtin.set_fact:
    archlinux_install_kernel: linux-cachyos
  when:
  - "pacman_conf | default('/etc/pacman.conf') == '/etc/pacman.conf'"
  - archlinux_install_kernel == 'linux' or archlinux_install_kernel is undefined or archlinux_install_kernel == ''

- name: Add cachyos mirror packages into additional packages
  ansible.builtin.set_fact:
    archlinux_install_additional_packages: "{{ (archlinux_install_additional_packages | default([])) + ['cachyos-keyring', 'cachyos-mirrorlist', 'cachyos-v3-mirrorlist', 'cachyos-v4-mirrorlist', 'cachyos/pacman'] }}"
  when:
  - "pacman_conf | default('/etc/pacman.conf') == '/etc/pacman.conf'"
  - archlinux_install_packages is undefined or archlinux_install_packages | length < 1

- name: Add cachyos-zfs and other zfs utils into additional packages
  ansible.builtin.set_fact:
    # archlinux_install_dependencies: "{{ (archlinux_install_dependencies | default([])) + ['zfs-utils'] }}"
    archlinux_install_additional_packages: "{{ (archlinux_install_additional_packages | default([])) + ['cachyos-zfs', archlinux_install_kernel + '-zfs', 'zfs-utils'] }}"
  when:
  - "pacman_conf | default('/etc/pacman.conf') == '/etc/pacman.conf'"
  - archlinux_install_root_fstype == 'zfs'
