---
- name: "Create mountpoint btrfs temp path"
  ansible.builtin.file:
    path: "{{ subvolume.path }}"
    mode: "0755"
    state: directory

- name: Mount btrfs to temp path
  ansible.posix.mount:
    path: "{{ subvolume.path }}"
    src: "{{ subvolume.src }}"
    fstype: "btrfs"
    state: mounted
  tags:
  - molecule-idempotence-notest

- name: "Ensure subvolume exists"
  community.general.btrfs_subvolume:
    name: "{{ subvol.name }}"
    filesystem_device: "{{ subvol.device | default(omit) }}"
    filesystem_label: "{{ subvol.label | default(omit) }}"
    filesystem_uuid: "{{ subvol.uuid | default(omit) }}"
    default: "{{ subvol.default | default(omit) }}"
    automount: "{{ subvol.automount | default(omit) }}"
    recursive: "{{ subvol.recursive | default(omit) }}"
  loop: "{{ subvolume.subvols }}"
  loop_control:
    loop_var: subvol
    label: "{{ subvol.name }}"

- name: Disable CoW for subvols with disable_cow = true
  ansible.builtin.file:
    path: "{{ subvolume.path }}/{{ subvol.name }}"
    attributes: C
  loop: "{{ subvolume.subvols }}"
  loop_control:
    loop_var: subvol
    label: "{{ subvol.name }}"
  when: subvol.disable_cow | default(false)
  tags:
  - molecule-idempotence-notest

- name: Unmount btrfs from temp path
  ansible.posix.mount:
    path: "{{ subvolume.path }}"
    state: unmounted
  tags:
  - molecule-idempotence-notest
