---
- name: "HACK: Copy pacman.conf within docker container"
  ansible.builtin.copy:
    src: /etc/pacman.conf
    dest: /mnt/etc/pacman.conf
    mode: "0644"
    remote_src: true

- name: Install archlinux-keyring
  ansible.builtin.command:
    cmd: >-
      pacstrap -K /mnt archlinux-keyring{%- if ansible_architecture is search("arm") or ansible_architecture is search("aarch64") %} archlinuxarm-keyring{%- endif %}
  failed_when: false
  changed_when: false
