---
- name: Unmount and wipe partitions
  when: archlinux_install_wipe_drive
  block:
  - name: Check if mounted # noqa: var-naming[no-role-prefix]
    ansible.builtin.command:
      cmd: "findmnt /mnt"
    changed_when: false
    failed_when: false
    register: partitioning_findmnt

  - name: Unmount recursive # noqa: var-naming[no-role-prefix]
    ansible.builtin.command:
      cmd: "umount -A --recursive /mnt"
    failed_when: partitioning_umount_recursive.rc != 0
    changed_when: false
    register: partitioning_umount_recursive
    when: partitioning_findmnt.rc == 0

  - name: Remove filesystem from boot partition # noqa: var-naming[no-role-prefix]
    community.general.filesystem:
      dev: '{{ archlinux_install_boot_partition }}'
      state: absent
    register: partitioning_wipe_boot
    retries: 10
    delay: 5
    until: partitioning_wipe_boot is not failed

  - name: Remove filesystem from root partition # noqa: var-naming[no-role-prefix]
    community.general.filesystem:
      dev: '{{ archlinux_install_root_partition }}'
      state: absent
    register: partitioning_wipe_root
    retries: 10
    delay: 5
    until: partitioning_wipe_root is not failed

  - name: Wipe partitions # noqa: var-naming[no-role-prefix]
    ansible.builtin.command:
      cmd: "wipefs -a {{ archlinux_install_drive }}"
    failed_when: partitioning_wipefs.rc != 0
    changed_when: not partitioning_wipefs is skipped
    register: partitioning_wipefs
# end block Unmount and wipe partitions

- name: Create partitions
  community.general.parted:
    device: '{{ archlinux_install_drive }}'
    label: gpt
    number: 1
    part_end: "{{ archlinux_install_boot_partition_size | default('512MB') }}"
    name: boot
    flags: [boot, esp]
    state: present

- name: Create root partition
  community.general.parted:
    device: '{{ archlinux_install_drive }}'
    label: gpt
    number: 2
    part_start: "{{ archlinux_install_boot_partition_size | default('512MB') }}"
    part_end: "{{ '-' + archlinux_install_swap_size if archlinux_install_swap_partition | default(false) and archlinux_install_swap_size | length > 1 else '100%' }}"
    name: root
    state: present

- name: Create swap partition
  when:
  - archlinux_install_swap_partition | default(false)
  - archlinux_install_swap_size is defined
  - archlinux_install_swap_size | length > 1
  community.general.parted:
    device: '{{ archlinux_install_drive }}'
    label: gpt
    name: swap
    fs_type: linux-swap
    number: 3
    part_start: "-{{ archlinux_install_swap_size }}"
    state: present
