- name: Unmount and wipe partitions
  when: archlinux_install_wipe_drive
  block:
  - name: Check if mounted
    ansible.builtin.command:
      cmd: "findmnt /mnt"
    changed_when: false
    failed_when: false
    register: partitioning_findmnt

  - name: Unmount recursive
    ansible.builtin.command:
      cmd: "umount -A --recursive /mnt"
    failed_when: partitioning_umount_recursive.rc != 0
    changed_when: false
    register: partitioning_umount_recursive
    when: partitioning_findmnt.rc == 0

  - name: Remove filesystem from boot partition
    community.general.filesystem:
      dev: '{{ archlinux_install_boot_partition }}'
      state: absent
    register: partitioning_wipe_boot
    retries: 10
    delay: 5
    until: partitioning_wipe_boot is not failed

  - name: Remove filesystem from root partition
    community.general.filesystem:
      dev: '{{ archlinux_install_root_partition }}'
      state: absent
    register: partitioning_wipe_root
    retries: 10
    delay: 5
    until: partitioning_wipe_root is not failed

  - name: Wipe partitions
    ansible.builtin.command:
      cmd: "wipefs -a {{ archlinux_install_drive }}"
    failed_when: partitioning_wipefs.rc != 0
    changed_when: not partitioning_wipefs is skipped
    register: partitioning_wipefs
# end block Unmount and wipe partitions

- name: Create partitions
  community.general.parted:
    device: '{{ archlinux_install_drive }}'
    label: gpt
    number: 1
    part_end: 512MB
    name: boot
    flags: [boot, esp]
    state: present

- name: Create root partition
  community.general.parted:
    device: '{{ archlinux_install_drive }}'
    label: gpt
    number: 2
    part_start: 512MB
    part_end: 100%
    name: root
    state: present
