- name: "Create a swapfile in /mnt{{ archlinux_install_swapfile }}"
  community.general.filesize:
    path: "/mnt{{ archlinux_install_swapfile }}"
    size: "{{ archlinux_install_swapfile_size }}"
    owner: root
    group: root
    mode: "0600"

- name: Check swapfile is active
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      swapon | grep /mnt{{ archlinux_install_swapfile }}
  failed_when: false
  changed_when: swapfile_swapon_exists.stdout == ''
  register: swapfile_swapon_exists

- name: "Run mkswap on /mnt{{ archlinux_install_swapfile }}"
  ansible.builtin.command:
    cmd: "mkswap /mnt{{ archlinux_install_swapfile }}"
  failed_when: swapfile_mkswap.rc != 0
  changed_when: false
  register: swapfile_mkswap
  when: swapfile_swapon_exists.stdout == ''

- name: "Run swapon /mnt{{ archlinux_install_swapfile }}"
  ansible.builtin.command:
    cmd: "swapon /mnt{{ archlinux_install_swapfile }}"
  failed_when: swapfile_swapon.rc != 0
  changed_when: false
  register: swapfile_swapon
  when: swapfile_mkswap is not skipped

- name: Disable CoW for swapfile
  ansible.builtin.file:
    path: /mnt{{ archlinux_install_swapfile }}
    attributes: C
  when: archlinux_install_root_fstype == 'btrfs'
