FROM {{ item.image }}

ENV container=docker \
    ANSIBLE_USER=molecule \
    DEPLOY_GROUP=deployer \
    SUDO_GROUP={{'sudo' if 'debian' in item.image else 'wheel' }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo \
    procps \
    iproute2 \
    python3-pip python3-dev python3-setuptools python3-wheel python3-apt \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean \
    && touch -a -m -d "2 weeks ago" /var/lib/apt/lists/ \
    && set -xe \
    && groupadd -r ${ANSIBLE_USER} \
    && groupadd -r ${DEPLOY_GROUP} \
    && useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} \
    && usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} \
    && usermod -aG ${DEPLOY_GROUP} ${ANSIBLE_USER} \
    && sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

RUN mkdir -p /boot/ \
    && touch /boot/config.txt \
    && echo \
'disable_splash=0 \n\
boot_delay=5 \n\
dtoverlay=i2c-rtc,ds1307 \n\
temp_limit=75\n\
do_not_touch=this\n\
enable_uart=0\n\
dtparam=audio=off           \n\
dtparam=sd_poll_once     \n\
start_x=1 \n\
' > /boot/config.txt \
    && touch /boot/cmdline.txt \
    && echo "root=PARTUUID=76349364-D66C-4C19-B422-237A0D2DB9F5 rootfstype=ext4 rootwait net.ifnames=0 logo.nologo console=tty1" > /boot/cmdline.txt

STOPSIGNAL SIGRTMIN+3
VOLUME [ "/tmp", "/run", "/run/lock" ]
WORKDIR /
