- name: Check if helm exists
  ansible.builtin.command: "which helm"
  register: which_helm_command
  changed_when: false
  failed_when: false

- name: "Helm uninstall calico"
  run_once: true
  when: which_helm_command.rc == 0
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    release_state: absent
    wait_timeout: "{{ calico_uninstall_wait_timeout }}"

- name: Ensure the tigera-operator Namespace is removed
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: tigera-operator
    state: absent

- name: Remove calico helm repo
  when: which_helm_command.rc == 0
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
    state: absent
