- name: Ensure the tigera-operator Namespace exists.
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: tigera-operator
    state: present
  register: tigera_operator_ns

- name: Create configmap using server side apply
  when: calico_helm_values.installation.calicoNetwork.linuxDataplane | default("IpTables") == "BPF"
  kubernetes.core.k8s:
    namespace: tigera-operator
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: kubernetes-services-endpoint
      data:
        KUBERNETES_SERVICE_HOST: "{{ calico_k3s_service_host | default(ansible_ssh_host) }}"
        KUBERNETES_SERVICE_PORT: "{{ calico_k3s_service_port | default(6443) }}"
    apply: true
    server_side_apply:
      field_manager: ansible

- name: Get current calico helm version
  run_once: true
  when: not tigera_operator_ns.changed
  block:
  - name: Get calico helmrelease information
    kubernetes.core.helm_info:
      release_name: calico
      release_namespace: tigera-operator
      release_state:
      - deployed
    register: calico_helmrelease
  - name: Set current calico version fact
    ansible.builtin.set_fact:
      calico_installed_version: "{{ calico_helmrelease.status.app_version }}"
    when: calico_helmrelease.status.app_version is defined

- name: Add helm repo for calico
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts
    state: present
  register: calico_repo_add

- name: Separately update the repository cache
  kubernetes.core.helm:
    name: dummy
    namespace: kube-system
    state: absent
    update_repo_cache: true
  when: not calico_repo_add.changed

- name: "Helm deploy calico {{ calico_version }}"
  run_once: true
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    chart_version: "{{ calico_version }}"
    values: "{{ calico_helm_values | default({}) }}"
    wait: true
  when:
    calico_version != (calico_installed_version | default ("default_value"))
    or
    calico_helm_upgrade | default(false)


- name: Wait until default FelixConfiguration has manifested
  run_once: true
  kubernetes.core.k8s_info:
    api_version: "{{ felix_configuration_apiversion }}"
    kind: FelixConfiguration
    name: default
  register: felixconfig
  until: felixconfig.resources != []
  retries: 60
  delay: 1

- name: Patch FelixConfiguration
  run_once: true
  kubernetes.core.k8s_json_patch:
    api: "{{ felix_configuration_apiversion }}"
    kind: FelixConfiguration
    name: default
    patch:
    - op: add
      path: /spec/iptablesBackend
      value: "{{ calico_iptables_backend | default('Auto') }}"
    - op: add
      path: /spec/logFilePath
      value: "{{ 'none' if calico_disable_file_logging | default(true) else '/var/log/calico/felix.log' }}"
    - op: add
      path: /spec/bpfExternalServiceMode
      value: "{{ 'DSR' if calico_enable_bpf_dsr | default(false) else 'Tunnel' }}"
    - op: add
      path: /spec/ipv6Support
      value: "{{ calico_enable_ipv6 | default(false) }}"
