---
- name: Uninstall calico
  environment:
    K8S_AUTH_KUBECONFIG: "{{ calico_kubeconfig }}"
  block:
  - name: Increment the retry count # noqa: var-naming[no-role-prefix]
    ansible.builtin.set_fact:
      retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"
  - name: "Helm uninstall calico" # noqa: var-naming[no-role-prefix]
    failed_when: false
    kubernetes.core.helm:
      name: calico
      chart_ref: projectcalico/tigera-operator
      release_namespace: tigera-operator
      release_state: absent
      # wait: true
      wait_timeout: "{{ calico_uninstall_wait_timeout }}"
    register: helm_uninstall_calico
  - name: Debug output
    ansible.builtin.debug:
      var: helm_uninstall_calico

  always:
  - name: Check if need to retry
    when: helm_uninstall_calico.stderr != ""
    block:
    - name: Fail if uninstall retries has been reached
      ansible.builtin.fail:
        msg: Maximum retries uninstall has reached
      when: retry_count | int == calico_uninstall_retries

    - name: Remove failed uninstall job
      kubernetes.core.k8s:
        api_version: batch/v1
        kind: Job
        name: tigera-operator-uninstall
        namespace: tigera-operator
        state: absent

    - name: Retry calico helm chart uninstall
      ansible.builtin.include_tasks: helm-uninstall.yml
# end block Uninstall calico
