---

- name: Detect CPU arch
  ansible.builtin.set_fact:
    calicoctl_cpu_arch: |-
      {%- if (ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "64") or ansible_facts.architecture is search("aarch64") -%}
        arm64
      {%- elif ansible_facts.architecture is search("arm") and ansible_facts.userspace_bits == "32" -%}
        armv7
      {%- elif ansible_facts.architecture == "x86_64" -%}
        amd64
      {%- elif ansible_facts.architecture in ["s390x", "ppc64le"] -%}
        {{ ansible_facts.architecture }}
      {%- endif -%}

- name: "Download calicoctl binary {{ calicoctl_cpu_arch }}"
  ansible.builtin.get_url:
    url: "https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/calicoctl-linux-{{ calicoctl_cpu_arch }}"
    checksum: sha256:https://github.com/projectcalico/calico/releases/download/{{ calico_version }}/SHA256SUMS
    dest: "{{ calico_ctl_install_path }}/kubectl-calico"
    owner: root
    group: root
    mode: "0755"
  register: calicoctl_dl
  retries: 10
  until: calicoctl_dl is success

- name: Create calicoctl symlink
  ansible.builtin.file:
    src: "{{ calico_ctl_install_path }}/kubectl-calico"
    dest: "{{ calico_ctl_install_path }}/calicoctl"
    state: link
  when:
  - calicoctl_dl is success
