---
# tasks file for calico
- name: Set calico version
  when: calico_version | default("latest") == "latest"
  run_once: true
  block:
  - name: Get list of calico github releases
    ansible.builtin.uri:
      url: https://api.github.com/repos/projectcalico/calico/releases/latest
      return_content: true
    register: calico_releases_json
  - name: Set calico latest as fact
    ansible.builtin.set_fact:
      calico_version: "{{ calico_releases_json.json.tag_name | trim }}"
    when: not calico_releases_json.failed

- name: Install python pre-requisites
  ansible.builtin.pip:
    name:
    - kubernetes

- name: Check if can access cluster with kubectl
  become: true
  ansible.builtin.command: "kubectl get nodes"
  register: kubectl_command
  failed_when: false
  changed_when: false

- name: Install calico with helm
  ansible.builtin.include_tasks: helm-install.yml
  when:
  - kubectl_command.rc == 0

- name: Install calicoctl
  ansible.builtin.import_tasks: kubectl-calicoctl-plugin.yml
  become: true
  when:
  - calico_ctl_install | default(false)

- name: Use k3s_bin_dir as calico_k3s_killalld_dir value if defined
  when: k3s_bin_dir is defined
  ansible.builtin.set_fact:
    calico_k3s_killalld_dir: "{{ k3s_bin_dir }}/k3s-killall.sh.d/"

- name: Copy remove calico cleanup script to k3s-killall.sh.d
  become: true
  when:
  - calico_k3s_killall_script | default(false)
  - calico_k3s_killalld_dir | default("") | length > 1
  ansible.builtin.template:
    src: "99-remove-calico-interfaces.sh.j2"
    dest: "{{ calico_k3s_killalld_dir }}/99-remove-calico-interfaces.sh"
    owner: root
    group: root
    mode: "0700"
