---
- name: Resolve default kubeconfig path
  ansible.builtin.command: "realpath {{ default_kubeconfig_path }}"
  register: realpath_kubeconfig_command
  failed_when: false
  changed_when: false

- name: Set calico_kubeconfig fact
  ansible.builtin.set_fact:
    calico_kubeconfig: "{{ realpath_kubeconfig_command.stdout | trim if realpath_kubeconfig_command.rc == 0 else calico_default_kubeconfig }}"
