---
- name: Resolve default kubeconfig path
  ansible.builtin.command: "realpath {{ calico_default_kubeconfig_path }}"
  register: realpath_kubeconfig_command
  failed_when: false
  changed_when: false

- name: "Stat kubeconfg"
  ansible.builtin.stat:
    path: "{{ realpath_kubeconfig_command.stdout }}"
  register: kubeconfig_file

- name: Set calico_kubeconfig fact
  ansible.builtin.set_fact:
    calico_kubeconfig: "{{ realpath_kubeconfig_command.stdout | trim if kubeconfig_file.stat.exists else calico_default_kubeconfig }}"
