- name: Check if can access cluster with kubectl
  ansible.builtin.command: "kubectl get nodes"
  register: kubectl_command
  failed_when: false
  changed_when: false

- name: Uninstall calico helm chart
  ansible.builtin.include_tasks: helm-uninstall.yml
  when:
  - kubectl_command.rc == 0

- name: Check if calicoctl exists
  ansible.builtin.command: "which calicoctl"
  register: which_calicoctl_command
  changed_when: false
  failed_when: false

- name: Remove calicoctl
  become: true
  when: which_calicoctl_command.rc == 0
  ansible.builtin.file:
    path: "{{ which_calicoctl_command.stdout | trim }}"
    state: absent

- name: Check if calicoctl exists
  ansible.builtin.command: "which kubectl-calico"
  register: which_kubectl_calico_command
  changed_when: false
  failed_when: false

- name: Remove calicoctl
  become: true
  when: which_kubectl_calico_command.rc == 0
  ansible.builtin.file:
    path: "{{ which_kubectl_calico_command.stdout | trim }}"
    state: absent

- name: Remove k3s-killall.sh.d script
  become: true
  when: calico_uninstall_remove_killall_script
  ansible.builtin.file:
    path: "{{ calico_k3s_killalld_dir }}/99-remove-calico-interfaces.sh"
    state: absent
