- name: Get current user name
  ansible.builtin.command: whoami
  register: whoami_command
  changed_when: whoami_command.rc != 0

- name: Set current_user_name fact
  ansible.builtin.set_fact:
    current_user_name: "{{ whoami_command.stdout | trim  }}"

- name: Check if can access cluster with kubectl
  ansible.builtin.command: "kubectl get nodes"
  register: kubectl_command
  failed_when: false
  changed_when: false

- name: Uninstall calico helm chart
  when:
  - kubectl_command.rc == 0
  block:
  - name: Uninstall calico helm chart
    ansible.builtin.include_tasks: helm-uninstall.yml
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Check if calicoctl exists
  ansible.builtin.command: "which calicoctl"
  register: which_calicoctl_command
  changed_when: false
  failed_when: false

- name: Remove calicoctl
  become: true
  when: which_calicoctl_command.rc == 0
  ansible.builtin.file:
    path: "{{ which_calicoctl_command.stdout | trim }}"
    state: absent

- name: Check if calicoctl exists
  ansible.builtin.command: "which kubectl-calico"
  register: which_kubectl_calico_command
  changed_when: false
  failed_when: false

- name: Remove calicoctl
  become: true
  when: which_kubectl_calico_command.rc == 0
  ansible.builtin.file:
    path: "{{ which_kubectl_calico_command.stdout | trim }}"
    state: absent

- name: Remove k3s-killall.sh.d script
  become: true
  when: calico_uninstall_remove_killall_script | default(false)
  ansible.builtin.file:
    path: "{{ calico_k3s_killalld_dir }}/99-remove-calico-interfaces.sh"
    state: absent

- name: Ensure the tigera-operator Namespace is removed
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: tigera-operator
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Ensure the FelixConfiguration is removed
  run_once: true
  kubernetes.core.k8s:
    api_version: "{{ felix_configuration_apiversion }}"
    kind: FelixConfiguration
    name: default
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Ensure the calico Installation manifest is removed
  run_once: true
  kubernetes.core.k8s:
    api_version: "operator.tigera.io/v1"
    kind: Installation
    name: default
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Remove finalizers from Installation manifest
  run_once: true
  kubernetes.core.k8s_json_patch:
    api_version: "operator.tigera.io/v1"
    kind: Installation
    name: default
    patch:
    - op: remove
      path: /metadata/finalizers
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"


- name: Remove finalizers from calico-node service account
  run_once: true
  kubernetes.core.k8s_json_patch:
    api_version: v1
    kind: ServiceAccount
    name: calico-node
    namespace: calico-system
    patch:
    - op: remove
      path: /metadata/finalizers
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Delete calico-node service account
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: ServiceAccount
    name: calico-node
    namespace: calico-system
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Remove finalizers from calico-cni-plugin service account
  run_once: true
  kubernetes.core.k8s_json_patch:
    api_version: v1
    kind: ServiceAccount
    name: calico-cni-plugin
    namespace: calico-system
    patch:
    - op: remove
      path: /metadata/finalizers
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Delete calico-cni-plugin service account
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: ServiceAccount
    name: calico-cni-plugin
    namespace: calico-system
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"

- name: Ensure the calico-system Namespace is removed
  run_once: true
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: calico-system
    state: absent
  environment:
    K8S_AUTH_KUBECONFIG: "{{ (current_user_name == 'root') | ternary('/etc/rancher/k3s/k3s.yaml', '~/.kube/config') }}"
