---
dependency:
  name: shell
  command: "COLLECTION_INSTALL=false ${GITHUB_WORKSPACE:-..}/${GITHUB_REPOSITORY:-..}/tools/install-deps.sh"
driver:
  name: docker
platforms:
- name: client
  image: "debian:11"
  tmpfs:
  - /run
  - /tmp
  pre_build_image: false
  dockerfile: Dockerfile.client.j2
  tty: true
  networks:
  - name: kubernetes-secret
  docker_networks:
  - name: kubernetes-secret
- name: kubernetes-secret-server
  image: "debian:12"
  dockerfile: Dockerfile.server.j2
  groups:
  - kubernetes_server
  tmpfs:
  - /run
  - /tmp
  volumes:
  - /lib/modules:/lib/modules:ro
  privileged: true
  pre_build_image: false
  tty: true
  networks:
  - name: kubernetes-secret
  docker_networks:
  - name: kubernetes-secret
provisioner:
  name: ansible
  inventory:
    host_vars:
      client:
        kubernetes_secret_data:
        - name: test
          data:
            abc: "1"
            cde: "2"
        - name: test2
          namespace: kube-system
          data:
            fgh: "3"
            ijk: "4"
        - name: test3
          namespace: nonexistant-ns
          data:
            lmn: "5"
            opq: "6"
    group_vars:
      kubernetes_server:
        k3s_allow_swap: true
        k3s_kubelet_config:
          maxPods: 250
          shutdownGracePeriod: 30s
          shutdownGracePeriodCriticalPods: 10s
        k3s_role: server
        k3s_config:
          disable:
          - traefik
          cluster-cidr: 10.42.0.0/16
          service-cidr: 10.43.0.0/16
          cluster-dns: 10.43.0.10
          disable-cloud-controller: true
          kube-apiserver-arg:
          - default-not-ready-toleration-seconds=10
          - default-unreachable-toleration-seconds=10
          snapshotter: native
          write-kubeconfig-mode: 644
          kube-controller-manager-arg:
          - bind-address=0.0.0.0
          - terminated-pod-gc-threshold=10
          kube-proxy-arg:
          - metrics-bind-address=0.0.0.0
          kube-scheduler-arg:
          - bind-address=0.0.0.0
      all:
        ansible_user: molecule
verifier:
  name: ansible
