---
# defaults file for k3s
# k3s_config
# k3s_role
# k3s_datastore_endpoint
# k3s_kubelet_root_dir: /var/lib/kubelet
# k3s_data_dir: /var/lib/rancher/k3s
# k3s_node_labels
# k3s_node_taints
# k3s_kubelet_config:
#   maxPods: 250
# k3s_kubescheduler_config:
#   leaderElection:
#     leaderElect: true
#   clientConnection:
#     kubeconfig: /var/lib/rancher/k3s/server/cred/scheduler.kubeconfig
# k3s_kubeconfig_output_path
# k3s_kubeconfig_context_name
# k3s_kubeconfig_cluster_name
# k3s_kubeconfig_user_name
# k3s_kubeconfig_server
# k3s_server # can override config.yaml server value
# k3s_tls_san # can override config.yaml tls-san value
# k3s_cluster_cidr # can override config.yaml cluster-cidr value
# k3s_service_cidr # can override config.yaml service-cidr value
# k3s_cluster_dns # can override config.yaml cluster-dns value
# k3s_systemd_service_dependencies: # list of dependencies for systemd service template
# - var-lib-longhorn.mount
k3s_allow_cluster_init: true # joins multiple masters/server into same cluster if there are more than 2 in play
k3s_containerd_log_level: "warn" # Supported levels are: "trace", "debug", "info", "warn", "error", "fatal", "panic"
k3s_containerd_use_crun: true
k3s_delete_images_tar_after_first_start: false
k3s_download_images: true
k3s_allow_swap: false
k3s_systemd_enable: true
k3s_systemd_start: true
k3s_bin_dir: "/usr/local/bin"
k3s_install_type: notify
k3s_release_channel: stable
k3s_use_config_file: true
k3s_config:
  write-kubeconfig-mode: 644
  default-runtime: crun
# pause-image: rancher/mirrored-pause:3.9
