---
- name: Install Arch linux deps for directory_sync
  become: true
  community.general.pacman:
    name:
    - inotify-tools
    - rsync
    state: present
    update_cache: true
  tags:
  - molecule-idempotence-notest
