---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: helm-install-debian-11
  image: debian:11
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
- name: helm-install-debian-12
  image: debian:12
  dockerfile: ../../../../molecule-shared/Dockerfile.debian.j2
  pre_build_image: false
- name: helm-install-arch
  image: archlinux:base
  dockerfile: ../../../../molecule-shared/Dockerfile.archlinux.j2
  pre_build_image: false
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../..
  inventory:
    group_vars:
      all:
        ansible_user: molecule
        helm_tag: v3.12.1
verifier:
  name: ansible
