---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
- name: helm-install-debian-11
  image: debian:11
  dockerfile: Dockerfile.debian.j2
  pre_build_image: false
- name: helm-install-debian-12
  image: debian:12
  dockerfile: Dockerfile.debian.j2
  pre_build_image: false
- name: helm-install-arch
  image: archlinux:base
  dockerfile: Dockerfile.arch.j2
  pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_user: molecule
        helm_tag: v3.12.1
verifier:
  name: ansible
