- name: Provision dietpi hosts
  hosts: dietpi_hosts
  gather_facts: false
  tasks:
  - name: Include role dietpi_configure
    block:
    - name: Gather the package facts
      become: true
      ansible.builtin.package_facts:
        manager: auto
    rescue:
    - name: Install python3
      ansible.builtin.raw: "{{ item }}"
      changed_when: false
      loop:
      - apt-get update
      - apt-get -y install python3 python3-apt
      become: true
    # end block Include role dietpi_configure

  - name: Run dietpi_configure
    ansible.builtin.include_role:
      name: dietpi_configure
