---
- name: Setup zfs pools
  hosts: zfs_hosts
  tasks:
  - name: Include zfs role
    ansible.builtin.include_role:
      name: "zfs"
  tags:
  - zfs
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Configure network
  hosts: arch_linux_hosts
  roles:
  - role: "systemd_networkd"
  tags:
  - systemd_networkd
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Set up backups
  hosts: arch_linux_hosts
  roles:
  - role: "borg_backup"
  tags:
  - borg_backup
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Set up deadman key
  hosts: arch_linux_hosts
  roles:
  - role: "usb_deadman"
  tags:
  - usb_deadman
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Install other applications
  hosts: arch_linux_hosts
  roles:
  - role: "archlinux_configure"
  tags:
  - archlinux_configure
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Set up k3s
  hosts: k3s_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "k3s"
  tags:
  - k3s
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Set up cilium
  hosts: cilium_hosts
  roles:
  - role: "cilium"
  tags:
  - cilium
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Create cluster secrets
  hosts: kubectl_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "kubernetes_secret"
  tags:
  - kube-secrets
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Bootstrap FluxCD repository
  hosts: fluxcd_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "fluxcd"
  tags:
  - fluxcd
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"

- name: Set up lvm autosnapshot
  hosts: arch_linux_hosts
  roles:
  - role: "lvm_autosnapshot"
  tags:
  - lvm_autosnapshot
  vars:
    ansible_user: "{{ automation_user_name | default('ansible') }}"
