- name: Create output path
  hosts:
  - k3s_servers
  gather_facts: true
  tasks:
  - name: Set output path if not defined
    run_once: true
    delegate_to: localhost
    when:
    - k3s_kubeconfig_output_path | default('') == ''
    ansible.builtin.set_fact:
      k3s_kubeconfig_output_path: "{{ lookup('env', 'PWD') }}/output"
  - name: Create output path
    delegate_to: localhost
    run_once: true
    ansible.builtin.file:
      path: "{{ k3s_kubeconfig_output_path }}"
      state: directory
      mode: '0755'

- name: Download kubeconfig to output path
  hosts:
  - k3s_servers
  gather_facts: true
  vars_prompt:
  - name: kubeconfig_merged
    prompt: Kubeconfig output path (gets merged to output), enter space to not merge
    default: "{{ lookup('env', 'HOME') }}/.kube/config"
    private: false
  tasks:
  - name: Run fetch-kubeconfig in k3s role
    ansible.builtin.include_role:
      name: k3s
      tasks_from: fetch-kubeconfig
    vars:
      k3s_kubeconfig_merge_path: "{{ k3s_kubeconfig_output_path + '/kubeconfig' if (kubeconfig_merged | trim) == '' else kubeconfig_merged }}"
