- name: Create output path
  hosts:
  - k3s_servers
  gather_facts: true
  tasks:
  - name: Set output path if not defined
    run_once: true
    delegate_to: localhost
    when:
    - k3s_kubeconfig_output_path | default('') == ''
    ansible.builtin.set_fact:
      k3s_kubeconfig_output_path: "{{ lookup('env', 'PWD') }}/output"
  - name: Create output path
    delegate_to: localhost
    run_once: true
    ansible.builtin.file:
      path: "{{ k3s_kubeconfig_output_path }}"
      state: directory
      mode: '0755'

- name: Download kubeconfig to output path
  hosts:
  - k3s_servers
  gather_facts: true
  tasks:
  - name: Run fetch-kubeconfig in k3s role
    run_once: true
    ansible.builtin.include_role:
      name: k3s
      tasks_from: fetch-kubeconfig
