---
- name: Edit boot config
  hosts: rpi_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: raspi_boot_config
  tags:
  - boot_config

- name: Run package updates
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: update_os
  tags:
  - update_os

- name: Run lvm role against lvm_hosts group
  hosts: lvm_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: lvm
  tags:
  - lvm

- name: Install helm
  hosts: helm_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: helm
  tags:
  - helm

- name: Reboot if needed
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: reboot
  tags:
  - reboot

- name: Set up k3s cluster
  hosts: k3s_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "k3s"
  tags:
  - k3s

- name: Install calico
  hosts: calico_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "calico"
  tags:
  - calico

- name: Create cluster secrets
  hosts: kubectl_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "kubernetes_secret"

- name: Bootstrap FluxCD repository
  hosts: fluxcd_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "fluxcd"
  tags:
  - fluxcd
