- name: Add lvm to ssd nodes
  hosts: ssd_nodes
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: topolvm_prepare
  tags:
  - lvm

- name: Run preparation tasks for each nodes
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: raspi_boot_config
  - role: update_os
  - role: helm
  - role: reboot
  tags:
  - helm
  - update_os
  - boot_config

- name: Set up k3s cluster
  hosts: k3s_nodes
  roles:
  - role: "k3s"
  tags:
  - k3s

- name: Install calico
  hosts: k3s_nodes
  roles:
  - role: "calico"
  tags:
  - calico
