- name: Run os upgrades
  hosts: all
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: update_os
  - role: reboot
- name: Upgrade k3s cluster
  hosts: k3s_nodes
  roles:
  - role: "k3s"
  vars:
    k3s_skip_prepare: true

- name: Upgrade calico
  hosts: k3s_nodes
  roles:
  - role: "calico"
  vars:
    calico_helm_upgrade: true

- name: Bootstrap FluxCD repository
  hosts: fluxcd_nodes
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "fluxcd"
  tags:
  - fluxcd