---
- name: Update cluster secrets
  hosts: kubectl_hosts
  gather_facts: true
  any_errors_fatal: true
  roles:
  - role: "kubernetes_secret"
  vars:
    ansible_user: "{{ automation_user_name | default(ansible_user) }}"
