---
# defaults file for lvm
lvm_enable_fstrim: true
lvm_uninstall_wipe_fs: false
lvm_vgs: []
# - name: vg.data
#   pvs:
#   - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi0 #/dev/sda
#   - /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1 #/dev/sdb
#   lvols:
#   - name: test
#     fs:
#       type: ext4
#     size: 1g
#     opts: --type raid1 --mirrors 1 --nosync
#     mount:
#       path: /mnt/test
#       opts: nofail,x-systemd.device-timeout=15
#       boot: true
#   - thinpool: example_thinpool
#     size: 50%VG
lvm_lvols: []
# - name: example_lvol
#   vg: vg.data
#   # state: absent
#   thinpool: example_thinpool
#   size: 9g
#   # force: true
#   # resizefs: true
#   fs:
#     type: ext4
#   mount:
#     path: /mnt/example_data
#     opts: nofail,x-systemd.device-timeout=15
#     boot: true
