- name: "Create vg {{ vg.name }}"
  become: true
  community.general.lvg:
    vg: "{{ vg.name }}"
    pvs: "{{ ([vg.pvs] if vg.pvs is string else vg.pvs) | join(',') }}"
    pvresize: "{{ vg.pvresize | default(false) }}"
    pesize: "{{ vg.pesize | default(omit) }}"
    pv_options: "{{ vg.pv_options | default(omit) }}"
    vg_options: "{{ vg.vg_options | default(omit) }}"

- name: "Create lvols"
  when:
  - vg.lvols is defined
  - vg.lvols is not string
  - vg.lvols is iterable
  ansible.builtin.include_tasks: tasks/create-lvols-and-mount.yaml
  loop_control:
    loop_var: lvol
  vars:
    vg_name: "{{ vg.name }}"
  with_items: "{{ vg.lvols }}"
