name: Lint and test

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
  - cron: '0 0 * * 0' # weekly
jobs:
  lint:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-roles.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6
      - name: Get changed roles
        id: changed-roles
        uses: tj-actions/changed-files@v42
        with:
          dir_names: true
          dir_names_exclude_current_dir: true
          dir_names_max_depth: 2
          files: roles/**/*
          files_ignore: |
            roles/topolvm_prepare/**
            roles/reboot/**
            *.md
            **/*.md
            **/.yamllint
          json: true
          escape_json: false
  test-roles:
    name: Molecule test roles
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        role: ${{ fromJSON(needs.lint.outputs.matrix) }}
    if: ${{ needs.lint.outputs.matrix != '[]' && needs.lint.outputs.matrix != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
          sparse-checkout: |
            roles
            tools
            requirements.txt
            requirements.yml
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --all
          molecule_working_dir: ${{ github.repository }}/${{ matrix.role }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
  test-playbooks:
    name: Molecule test playbooks
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - end-to-end
          - multi-server-cluster
    if: github.event_name == 'pull_request' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"
          sparse-checkout: |
            molecule
            playbooks
            roles
            tools
            requirements.txt
            requirements.yml
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
