---
- name: Converge
  hosts: all

- name: Import create_cluster playbook
  ansible.builtin.import_playbook: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') | default('../..', true) }}/playbooks/create_cluster.yml"
