FROM {{ item.image }}
ENV POSTGRES_PASSWORD=postgres
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    sudo \
    procps \
    iproute2 \
    python3-pip python3-dev python3-setuptools python3-wheel python3-apt \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean