---
- name: Prepare
  hosts: all
  tasks:
  - name: Install dependencies
    become: true
    community.general.pacman:
      name:
      - mkinitcpio
      - linux
      state: present
      update_cache: true
    when:
    - ansible_facts['os_family'] == "Archlinux"
    tags:
    - molecule-idempotence-notest
